name: General Issue
description: Create an issue for developers to work on
title: "Issue"
body:
 - type: markdown
   attributes:
     value: |
      ## 💡 [Issue Title]

      ## 📝 Description
      -
      
      ## 🔢 Steps
      -
      ## ✅ Acceptance Criteria
      -
